### ISSUE TITLE
Failed to load SourceMap

### ISSUE THREAD

**Issue by marll** [marco-silvestri/boolbnb#126]
Salve,
avviando l'applicazione riscontro i seguenti warnings:
dashboard:21 Resource interpreted as Stylesheet but transferred with MIME type text/plain: "https://unpkg.com/tailwindcss@%5E1.0/dist/tailwind.min.css".
app.js:18793 [Violation] 'setTimeout' handler took 53ms
DevTools failed to load SourceMap: Could not load content for https://cdn.jsdelivr.net/npm/places.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://xmsoft.ikwb.com/boolbnb-master/public/js/popper.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://xmsoft.ikwb.com/boolbnb-master/public/js/es6-promise.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Durante la creazione dell'appartamento non viene riconosciuto l'indirizzo nè  caricata la foto.
Mi potreste dire come risolvere il problema?
Grazie

**Comment by marco-silvestri** [comment]
Salve,
purtroppo questa e' una app che non riceve piu' supporto, ne aggiornamenti, ne manutenzione.
